"""inisialisasi

Revision ID: 0b296652ed36
Revises: e110c8d7bddf
Create Date: 2026-05-06 19:50:05.631485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b296652ed36'
down_revision = 'e110c8d7bddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_guru',
    sa.Column('nip', sa.String(length=20), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('nip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_guru')
    # ### end Alembic commands ###
