"""tabel master_jam

Revision ID: 1e2d8581d0e3
Revises: a04992835335
Create Date: 2026-05-07 11:19:01.739214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2d8581d0e3'
down_revision = 'a04992835335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_jam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jam_mulai', sa.Time(), nullable=True),
    sa.Column('jam_selesai', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_jam')
    # ### end Alembic commands ###
