"""tambah kolom is_verified dan tabel master

Revision ID: 45afc60cfb52
Revises: 7cccbf8fdff2
Create Date: 2026-05-02 18:24:41.804860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45afc60cfb52'
down_revision = '7cccbf8fdff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_guru',
    sa.Column('nip', sa.String(length=20), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('nip')
    )
    op.create_table('master_siswa',
    sa.Column('nis', sa.String(length=20), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('nis')
    )
    with op.batch_alter_table('master_kelas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kelas', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('wali_kelas', sa.String(length=100), nullable=False))
        batch_op.alter_column('jurusan_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('nama_kelas')

    with op.batch_alter_table('master_mapel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kode_mapel', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('kelompok', sa.String(length=20), nullable=False))
        batch_op.drop_index(batch_op.f('nama_mapel'))
        batch_op.create_unique_constraint(None, ['kode_mapel'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('master_mapel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('nama_mapel'), ['nama_mapel'], unique=True)
        batch_op.drop_column('kelompok')
        batch_op.drop_column('kode_mapel')

    with op.batch_alter_table('master_kelas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_kelas', mysql.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('jurusan_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('wali_kelas')
        batch_op.drop_column('kelas')

    op.drop_table('master_siswa')
    op.drop_table('master_guru')
    # ### end Alembic commands ###
