"""final

Revision ID: 5e86572fa8bd
Revises: 
Create Date: 2026-04-03 20:35:21.315277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e86572fa8bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_jenis_surat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_jenis', sa.String(length=50), nullable=False),
    sa.Column('kode_surat', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_jurusan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_jurusan', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_jurusan')
    )
    op.create_table('master_mapel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_mapel', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_mapel')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admin_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('nip', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('no_hp', sa.String(length=15), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('guru_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nip', sa.String(length=20), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('gelar', sa.String(length=20), nullable=True),
    sa.Column('jenis_kelamin', sa.Enum('L', 'P'), nullable=False),
    sa.Column('no_hp', sa.String(length=15), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('kepsek_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nip', sa.String(length=20), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('periode_mulai', sa.Date(), nullable=True),
    sa.Column('periode_selesai', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('master_kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_kelas', sa.String(length=50), nullable=False),
    sa.Column('jurusan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jurusan_id'], ['master_jurusan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staf_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nip', sa.String(length=20), nullable=True),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('bagian', sa.String(length=50), nullable=True),
    sa.Column('no_hp', sa.String(length=15), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('siswa_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nisn', sa.String(length=20), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=50), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('jenis_kelamin', sa.Enum('L', 'P'), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('nama_ortu', sa.String(length=100), nullable=True),
    sa.Column('no_telp_ortu', sa.String(length=15), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=True),
    sa.Column('jurusan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jurusan_id'], ['master_jurusan.id'], ),
    sa.ForeignKeyConstraint(['kelas_id'], ['master_kelas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nisn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siswa_profile')
    op.drop_table('staf_profile')
    op.drop_table('master_kelas')
    op.drop_table('kepsek_profile')
    op.drop_table('guru_profile')
    op.drop_table('admin_profile')
    op.drop_table('users')
    op.drop_table('master_mapel')
    op.drop_table('master_jurusan')
    op.drop_table('master_jenis_surat')
    # ### end Alembic commands ###
