"""tambah kolom profil lengkap dan set nisn nullable

Revision ID: 7cccbf8fdff2
Revises: 99b357b0aa96
Create Date: 2026-04-07 14:14:36.386494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cccbf8fdff2'
down_revision = '99b357b0aa96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guru_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempat_lahir', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tanggal_lahir', sa.Date(), nullable=True))
        batch_op.alter_column('jenis_kelamin',
               existing_type=mysql.ENUM('L', 'P'),
               nullable=True)
        batch_op.alter_column('nip',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=True)

    with op.batch_alter_table('kepsek_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_kelamin', sa.Enum('L', 'P'), nullable=True))
        batch_op.add_column(sa.Column('tempat_lahir', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tanggal_lahir', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('alamat', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('no_hp', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('gelar', sa.String(length=20), nullable=True))
        batch_op.alter_column('nip',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.alter_column('periode_mulai',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('periode_selesai',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('siswa_profile', schema=None) as batch_op:
        batch_op.alter_column('nisn',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('jenis_kelamin',
               existing_type=mysql.ENUM('L', 'P'),
               nullable=True)

    with op.batch_alter_table('staf_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_kelamin', sa.Enum('L', 'P'), nullable=True))
        batch_op.add_column(sa.Column('tempat_lahir', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tanggal_lahir', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('alamat', sa.Text(), nullable=True))
        batch_op.alter_column('nip',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staf_profile', schema=None) as batch_op:
        batch_op.alter_column('nip',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('alamat')
        batch_op.drop_column('tanggal_lahir')
        batch_op.drop_column('tempat_lahir')
        batch_op.drop_column('jenis_kelamin')

    with op.batch_alter_table('siswa_profile', schema=None) as batch_op:
        batch_op.alter_column('jenis_kelamin',
               existing_type=mysql.ENUM('L', 'P'),
               nullable=False)
        batch_op.alter_column('nisn',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('kepsek_profile', schema=None) as batch_op:
        batch_op.alter_column('periode_selesai',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('periode_mulai',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('nip',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('gelar')
        batch_op.drop_column('no_hp')
        batch_op.drop_column('alamat')
        batch_op.drop_column('tanggal_lahir')
        batch_op.drop_column('tempat_lahir')
        batch_op.drop_column('jenis_kelamin')

    with op.batch_alter_table('guru_profile', schema=None) as batch_op:
        batch_op.alter_column('nip',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('jenis_kelamin',
               existing_type=mysql.ENUM('L', 'P'),
               nullable=False)
        batch_op.drop_column('tanggal_lahir')
        batch_op.drop_column('tempat_lahir')

    # ### end Alembic commands ###
