"""reset clean

Revision ID: 7e3f7c82b3f9
Revises: 
Create Date: 2026-05-05 21:16:33.006603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3f7c82b3f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_guru',
    sa.Column('nip', sa.String(length=20), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('nip')
    )
    op.create_table('master_jurusan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_jurusan', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_jurusan')
    )
    op.create_table('master_mapel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_mapel', sa.String(length=20), nullable=False),
    sa.Column('nama_mapel', sa.String(length=50), nullable=False),
    sa.Column('kelompok', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_mapel')
    )
    op.create_table('master_siswa',
    sa.Column('nis', sa.String(length=20), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('nis')
    )
    op.create_table('presensiqr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapel', sa.String(length=50), nullable=False),
    sa.Column('kelas', sa.String(length=50), nullable=False),
    sa.Column('jam', sa.String(length=20), nullable=False),
    sa.Column('waktu', sa.DateTime(), nullable=True),
    sa.Column('guru_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admin_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('nip', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('no_hp', sa.String(length=15), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('guru_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('jenis_kelamin', sa.Enum('L', 'P'), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=50), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('no_hp', sa.String(length=15), nullable=True),
    sa.Column('nip', sa.String(length=30), nullable=True),
    sa.Column('gelar', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('master_kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kelas', sa.String(length=50), nullable=False),
    sa.Column('jurusan_id', sa.Integer(), nullable=False),
    sa.Column('wali_kelas', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['jurusan_id'], ['master_jurusan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staf_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('jenis_kelamin', sa.Enum('L', 'P'), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=50), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('no_hp', sa.String(length=15), nullable=True),
    sa.Column('nip', sa.String(length=30), nullable=True),
    sa.Column('bagian', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('jadwal_pelajaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.Column('mapel_id', sa.Integer(), nullable=False),
    sa.Column('guru_id', sa.Integer(), nullable=False),
    sa.Column('hari', sa.String(length=20), nullable=False),
    sa.Column('jam_mulai', sa.Time(), nullable=False),
    sa.Column('jam_selesai', sa.Time(), nullable=False),
    sa.Column('semester', sa.String(length=10), nullable=True),
    sa.Column('tahun_ajaran', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['guru_id'], ['guru_profile.id'], ),
    sa.ForeignKeyConstraint(['kelas_id'], ['master_kelas.id'], ),
    sa.ForeignKeyConstraint(['mapel_id'], ['master_mapel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siswa_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nisn', sa.String(length=20), nullable=True),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=50), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('jenis_kelamin', sa.Enum('L', 'P'), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('nama_ortu', sa.String(length=100), nullable=True),
    sa.Column('no_telp_ortu', sa.String(length=15), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=True),
    sa.Column('jurusan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jurusan_id'], ['master_jurusan.id'], ),
    sa.ForeignKeyConstraint(['kelas_id'], ['master_kelas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nisn')
    )
    op.create_table('presensi_harian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('jam_masuk', sa.DateTime(), nullable=True),
    sa.Column('jam_pulang', sa.DateTime(), nullable=True),
    sa.Column('foto_bukti', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presensi_siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presensi_id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('mapel', sa.String(length=100), nullable=False),
    sa.Column('kelas', sa.String(length=50), nullable=False),
    sa.Column('jam', sa.String(length=20), nullable=False),
    sa.Column('waktu_scan', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['presensi_id'], ['presensiqr.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('presensi_id', 'siswa_id', name='unique_presensi_siswa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presensi_siswa')
    op.drop_table('presensi_harian')
    op.drop_table('siswa_profile')
    op.drop_table('jadwal_pelajaran')
    op.drop_table('staf_profile')
    op.drop_table('master_kelas')
    op.drop_table('guru_profile')
    op.drop_table('admin_profile')
    op.drop_table('users')
    op.drop_table('presensiqr')
    op.drop_table('master_siswa')
    op.drop_table('master_mapel')
    op.drop_table('master_jurusan')
    op.drop_table('master_guru')
    # ### end Alembic commands ###
