"""mengubah foto_bukti menjadi text

Revision ID: 9165eaa1c509
Revises: d3b936c7cdaf
Create Date: 2026-05-03 17:07:08.150071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9165eaa1c509'
down_revision = 'd3b936c7cdaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presensi_harian', schema=None) as batch_op:
        batch_op.alter_column('foto_bukti',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presensi_harian', schema=None) as batch_op:
        batch_op.alter_column('foto_bukti',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
