"""create table presensi_harian

Revision ID: 99b357b0aa96
Revises: 5e86572fa8bd
Create Date: 2026-04-07 11:25:20.593389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b357b0aa96'
down_revision = '5e86572fa8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presensi_harian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('jam_masuk', sa.DateTime(), nullable=True),
    sa.Column('jam_pulang', sa.DateTime(), nullable=True),
    sa.Column('foto_bukti', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presensi_harian')
    # ### end Alembic commands ###
