"""create table master_jam

Revision ID: a04992835335
Revises: 0b296652ed36
Create Date: 2026-05-07 10:39:52.352945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a04992835335'
down_revision = '0b296652ed36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presensi_siswa', schema=None) as batch_op:
        batch_op.drop_column('mapel')
        batch_op.drop_column('kelas')
        batch_op.drop_column('jam')

    with op.batch_alter_table('presensiqr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_token', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['qr_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presensiqr', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('qr_token')

    with op.batch_alter_table('presensi_siswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jam', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('kelas', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('mapel', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
