"""fix master guru primary key

Revision ID: cbaa26ad7c1c
Revises: 5ca1065acf22
Create Date: 2026-05-07 19:00:12.345885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbaa26ad7c1c'
down_revision = '5ca1065acf22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_guru', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('nip'))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_guru', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('nip'), ['nip'], unique=True)

    # ### end Alembic commands ###
