"""inisialisasi

Revision ID: e110c8d7bddf
Revises: 7e3f7c82b3f9
Create Date: 2026-05-06 19:34:06.188910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e110c8d7bddf'
down_revision = '7e3f7c82b3f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_guru')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_guru',
    sa.Column('nip', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nama_lengkap', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('nip'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
